#generated by django 5.2.6 on 2025-11-07 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='chat_bloqueado',
            field=models.BooleanField(default=False, verbose_name='Chat Bloqueado'),
        ),
    ]
