#generated by django 5.2.7 on 2025-11-08 15:13

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicidad', '0002_remove_itemsolicitud_espacio_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UbicacionPublicidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('tipo', models.CharField(choices=[('panel_izquierdo', 'Panel Lateral Izquierdo'), ('panel_derecho', 'Panel Lateral Derecho'), ('banner_superior_home', 'Banner Superior Home (debajo navbar)'), ('banner_articulos', 'Banner Debajo de Últimos Artículos')], max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('dimensiones', models.CharField(help_text='Ej: 300x600, 728x90', max_length=50)),
                ('precio_mensual', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('activo', models.BooleanField(default=True, help_text='Si está disponible para contratar')),
                ('orden', models.IntegerField(default=0, help_text='Orden de visualización en catálogo')),
            ],
            options={
                'verbose_name': 'Ubicación de Publicidad',
                'verbose_name_plural': 'Ubicaciones de Publicidad',
                'db_table': 'ubicacion_publicidad',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='SolicitudPublicidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_contacto', models.CharField(max_length=150)),
                ('email_contacto', models.EmailField(max_length=254)),
                ('telefono_contacto', models.CharField(blank=True, max_length=20, null=True)),
                ('whatsapp_contacto', models.CharField(blank=True, max_length=20, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_revision', 'En Revisión'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada'), ('activa', 'Activa (publicándose)'), ('finalizada', 'Finalizada')], default='pendiente', max_length=20)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('fecha_inicio_solicitada', models.DateField()),
                ('fecha_fin_solicitada', models.DateField()),
                ('mensaje_usuario', models.TextField(blank=True, help_text='Mensaje o comentarios del usuario', null=True)),
                ('notas_admin', models.TextField(blank=True, help_text='Notas internas del administrador', null=True)),
                ('motivo_rechazo', models.TextField(blank=True, null=True)),
                ('costo_total_estimado', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('publicidad_aprobada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitud_origen', to='publicidad.publicidad')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_publicidad', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solicitud de Publicidad',
                'verbose_name_plural': 'Solicitudes de Publicidad',
                'db_table': 'solicitud_publicidad',
                'ordering': ['-fecha_solicitud'],
            },
        ),
        migrations.CreateModel(
            name='ItemSolicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_destino', models.URLField(blank=True, help_text='Link al que redirige la publicidad', max_length=500, null=True)),
                ('precio_acordado', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('notas', models.TextField(blank=True, null=True)),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='publicidad.solicitudpublicidad')),
                ('ubicacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items_solicitud', to='publicidad.ubicacionpublicidad')),
            ],
            options={
                'verbose_name': 'Item de Solicitud',
                'verbose_name_plural': 'Items de Solicitud',
                'db_table': 'item_solicitud',
            },
        ),
        migrations.CreateModel(
            name='ImagenPublicidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(help_text='Imagen para la publicidad', upload_to='publicidad/solicitudes/%Y/%m/')),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
                ('orden', models.IntegerField(default=0, help_text='Orden si hay múltiples imágenes')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='publicidad.itemsolicitud')),
            ],
            options={
                'verbose_name': 'Imagen de Publicidad',
                'verbose_name_plural': 'Imágenes de Publicidad',
                'db_table': 'imagen_publicidad',
                'ordering': ['orden', 'fecha_subida'],
                'indexes': [models.Index(fields=['item'], name='imagen_publ_item_id_503e91_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='solicitudpublicidad',
            index=models.Index(fields=['usuario'], name='solicitud_p_usuario_abf381_idx'),
        ),
        migrations.AddIndex(
            model_name='solicitudpublicidad',
            index=models.Index(fields=['estado'], name='solicitud_p_estado_d612f3_idx'),
        ),
        migrations.AddIndex(
            model_name='solicitudpublicidad',
            index=models.Index(fields=['fecha_solicitud'], name='solicitud_p_fecha_s_832f71_idx'),
        ),
        migrations.AddConstraint(
            model_name='solicitudpublicidad',
            constraint=models.CheckConstraint(condition=models.Q(('fecha_fin_solicitada__gte', models.F('fecha_inicio_solicitada'))), name='solicitud_fechas_validas'),
        ),
        migrations.AddIndex(
            model_name='itemsolicitud',
            index=models.Index(fields=['solicitud'], name='item_solici_solicit_f6ca04_idx'),
        ),
        migrations.AddIndex(
            model_name='itemsolicitud',
            index=models.Index(fields=['ubicacion'], name='item_solici_ubicaci_b670a6_idx'),
        ),
    ]
