#generated by django 5.2.7 on 2025-11-08 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicidad', '0003_ubicacionpublicidad_solicitudpublicidad_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='publicidad',
            name='publicidad_usuario_0bcea4_idx',
        ),
        migrations.RemoveField(
            model_name='publicidad',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='solicitudpublicidad',
            name='publicidad_aprobada',
        ),
        migrations.RemoveField(
            model_name='solicitudpublicidad',
            name='whatsapp_contacto',
        ),
        migrations.AddField(
            model_name='publicidad',
            name='item_solicitud',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publicidades', to='publicidad.itemsolicitud'),
        ),
        migrations.AddField(
            model_name='solicitudpublicidad',
            name='preferencia_contacto',
            field=models.CharField(choices=[('telefono', 'Teléfono'), ('whatsapp', 'WhatsApp'), ('email', 'Email')], default='telefono', max_length=20),
        ),
        migrations.AddIndex(
            model_name='publicidad',
            index=models.Index(fields=['item_solicitud'], name='publicidad_item_so_1e93c5_idx'),
        ),
    ]
