#generated by django 5.2.7 on 2025-11-08 17:42

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicidad', '0006_itemsolicitud_formato'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivoPublicidadRadial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(help_text='Archivo de audio para la publicidad radial', upload_to='publicidad/radial/solicitudes/%Y/%m/', verbose_name='Archivo de Audio')),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True, verbose_name='Descripción')),
                ('orden', models.IntegerField(default=0, help_text='Orden de visualización si hay múltiples archivos', verbose_name='Orden')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Subida')),
            ],
            options={
                'verbose_name': 'Archivo de Publicidad Radial',
                'verbose_name_plural': 'Archivos de Publicidad Radial',
                'db_table': 'archivo_publicidad_radial',
                'ordering': ['orden', 'fecha_subida'],
            },
        ),
        migrations.CreateModel(
            name='ImagenPublicidadWeb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(help_text='Imagen para la publicidad web', upload_to='publicidad/web/solicitudes/%Y/%m/', verbose_name='Archivo de Imagen')),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True, verbose_name='Descripción')),
                ('orden', models.IntegerField(default=0, help_text='Orden de visualización si hay múltiples imágenes', verbose_name='Orden')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Subida')),
            ],
            options={
                'verbose_name': 'Imagen de Publicidad Web',
                'verbose_name_plural': 'Imágenes de Publicidad Web',
                'db_table': 'imagen_publicidad_web',
                'ordering': ['orden', 'fecha_subida'],
            },
        ),
        migrations.CreateModel(
            name='ItemSolicitudRadial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_destino', models.URLField(help_text='Link al que redirige la publicidad', max_length=500, verbose_name='URL de Destino')),
                ('formato', models.CharField(help_text='Dimensiones del banner (ej: 728x90)', max_length=50, verbose_name='Formato')),
                ('precio_acordado', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Precio Acordado')),
                ('notas', models.TextField(blank=True, null=True, verbose_name='Notas')),
            ],
            options={
                'verbose_name': 'Item de Solicitud Radial',
                'verbose_name_plural': 'Items de Solicitud Radial',
                'db_table': 'item_solicitud_radial',
            },
        ),
        migrations.CreateModel(
            name='ItemSolicitudWeb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_destino', models.URLField(help_text='Link al que redirige la publicidad', max_length=500, verbose_name='URL de Destino')),
                ('formato', models.CharField(help_text='Dimensiones del banner (ej: 728x90)', max_length=50, verbose_name='Formato')),
                ('precio_acordado', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Precio Acordado')),
                ('notas', models.TextField(blank=True, null=True, verbose_name='Notas')),
            ],
            options={
                'verbose_name': 'Item de Solicitud Web',
                'verbose_name_plural': 'Items de Solicitud Web',
                'db_table': 'item_solicitud_web',
            },
        ),
        migrations.CreateModel(
            name='PublicidadWeb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_destino', models.URLField(max_length=500, verbose_name='URL de Destino')),
                ('formato', models.CharField(max_length=50, verbose_name='Formato (ej: 728x90)')),
                ('impresiones', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Número de Impresiones')),
                ('clics', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Número de Clics')),
                ('archivo_media', models.URLField(blank=True, max_length=500, null=True, verbose_name='URL del Archivo Multimedia')),
            ],
            options={
                'verbose_name': 'Configuración Web',
                'verbose_name_plural': 'Configuraciones Web',
                'db_table': 'publicidad_web',
            },
        ),
        migrations.CreateModel(
            name='SolicitudPublicidadRadial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_contacto', models.CharField(max_length=150, verbose_name='Nombre de Contacto')),
                ('email_contacto', models.EmailField(max_length=254, verbose_name='Email de Contacto')),
                ('telefono_contacto', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono de Contacto')),
                ('preferencia_contacto', models.CharField(choices=[('telefono', 'Teléfono'), ('whatsapp', 'WhatsApp'), ('email', 'Email')], default='telefono', max_length=20, verbose_name='Preferencia de Contacto')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_revision', 'En Revisión'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada'), ('activa', 'Activa (publicándose)'), ('finalizada', 'Finalizada')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Solicitud')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('fecha_inicio_solicitada', models.DateField(verbose_name='Fecha de Inicio Solicitada')),
                ('fecha_fin_solicitada', models.DateField(verbose_name='Fecha de Finalización Solicitada')),
                ('mensaje_usuario', models.TextField(blank=True, help_text='Mensaje o comentarios del usuario', null=True, verbose_name='Mensaje del Usuario')),
                ('notas_admin', models.TextField(blank=True, help_text='Notas internas del administrador', null=True, verbose_name='Notas del Administrador')),
                ('motivo_rechazo', models.TextField(blank=True, null=True, verbose_name='Motivo de Rechazo')),
                ('costo_total_estimado', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Costo Total Estimado')),
            ],
            options={
                'verbose_name': 'Solicitud de Publicidad Radial',
                'verbose_name_plural': 'Solicitudes de Publicidad Radial',
                'db_table': 'solicitud_publicidad_radial',
                'ordering': ['-fecha_solicitud'],
            },
        ),
        migrations.CreateModel(
            name='SolicitudPublicidadWeb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_contacto', models.CharField(max_length=150, verbose_name='Nombre de Contacto')),
                ('email_contacto', models.EmailField(max_length=254, verbose_name='Email de Contacto')),
                ('telefono_contacto', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono de Contacto')),
                ('preferencia_contacto', models.CharField(choices=[('telefono', 'Teléfono'), ('whatsapp', 'WhatsApp'), ('email', 'Email')], default='telefono', max_length=20, verbose_name='Preferencia de Contacto')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_revision', 'En Revisión'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada'), ('activa', 'Activa (publicándose)'), ('finalizada', 'Finalizada')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Solicitud')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('fecha_inicio_solicitada', models.DateField(verbose_name='Fecha de Inicio Solicitada')),
                ('fecha_fin_solicitada', models.DateField(verbose_name='Fecha de Finalización Solicitada')),
                ('mensaje_usuario', models.TextField(blank=True, help_text='Mensaje o comentarios del usuario', null=True, verbose_name='Mensaje del Usuario')),
                ('notas_admin', models.TextField(blank=True, help_text='Notas internas del administrador', null=True, verbose_name='Notas del Administrador')),
                ('motivo_rechazo', models.TextField(blank=True, null=True, verbose_name='Motivo de Rechazo')),
                ('costo_total_estimado', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Costo Total Estimado')),
            ],
            options={
                'verbose_name': 'Solicitud de Publicidad Web',
                'verbose_name_plural': 'Solicitudes de Publicidad Web',
                'db_table': 'solicitud_publicidad_web',
                'ordering': ['-fecha_solicitud'],
            },
        ),
        migrations.CreateModel(
            name='UbicacionPublicidadRadial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre de la Ubicación')),
                ('tipo', models.CharField(choices=[('spot', 'Spot'), ('bloque', 'Bloque')], max_length=50, unique=True, verbose_name='Tipo de Ubicación')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('duracion', models.IntegerField(verbose_name='Duración en segundos')),
                ('precio_mensual', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Precio Mensual')),
                ('activo', models.BooleanField(default=True, help_text='¿Está disponible para contratar?', verbose_name='¿Activo?')),
                ('orden', models.IntegerField(default=0, help_text='Orden de visualización en catálogo', verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Ubicación de Publicidad Radial',
                'verbose_name_plural': 'Ubicaciones de Publicidad Radial',
                'db_table': 'ubicacion_publicidad_radial',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='UbicacionPublicidadWeb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre de la Ubicación')),
                ('tipo', models.CharField(choices=[('panel_izquierdo', 'Panel Lateral Izquierdo'), ('panel_derecho', 'Panel Lateral Derecho'), ('banner_superior_home', 'Banner Superior Home (debajo navbar)'), ('banner_articulos', 'Banner Debajo de Últimos Artículos')], max_length=50, unique=True, verbose_name='Tipo de Ubicación')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('dimensiones', models.CharField(help_text='Ej: 300x600, 728x90', max_length=50, verbose_name='Dimensiones')),
                ('precio_mensual', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Precio Mensual')),
                ('activo', models.BooleanField(default=True, help_text='¿Está disponible para contratar?', verbose_name='¿Activo?')),
                ('orden', models.IntegerField(default=0, help_text='Orden de visualización en catálogo', verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Ubicación de Publicidad Web',
                'verbose_name_plural': 'Ubicaciones de Publicidad Web',
                'db_table': 'ubicacion_publicidad_web',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.RemoveField(
            model_name='imagenpublicidad',
            name='item',
        ),
        migrations.RemoveField(
            model_name='itemsolicitud',
            name='solicitud',
        ),
        migrations.RemoveField(
            model_name='itemsolicitud',
            name='ubicacion',
        ),
        migrations.RemoveField(
            model_name='publicidad',
            name='item_solicitud',
        ),
        migrations.RemoveField(
            model_name='publicidadradial',
            name='horario',
        ),
        migrations.RemoveField(
            model_name='publicidadradial',
            name='publicidad',
        ),
        migrations.RemoveField(
            model_name='solicitudpublicidad',
            name='usuario',
        ),
        migrations.AlterModelOptions(
            name='publicidad',
            options={'ordering': ['-fecha_creacion'], 'verbose_name': 'Publicidad', 'verbose_name_plural': 'Publicidades'},
        ),
        migrations.RemoveIndex(
            model_name='publicidad',
            name='publicidad_item_so_1e93c5_idx',
        ),
        migrations.RemoveField(
            model_name='publicidad',
            name='archivo_media',
        ),
        migrations.RemoveField(
            model_name='publicidad',
            name='clics',
        ),
        migrations.RemoveField(
            model_name='publicidad',
            name='formato',
        ),
        migrations.RemoveField(
            model_name='publicidad',
            name='impresiones',
        ),
        migrations.RemoveField(
            model_name='publicidad',
            name='url_destino',
        ),
        migrations.AlterField(
            model_name='publicidad',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='¿Activo?'),
        ),
        migrations.AlterField(
            model_name='publicidad',
            name='costo_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Costo Total'),
        ),
        migrations.AlterField(
            model_name='publicidad',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='publicidad',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación'),
        ),
        migrations.AlterField(
            model_name='publicidad',
            name='fecha_fin',
            field=models.DateField(verbose_name='Fecha de Finalización'),
        ),
        migrations.AlterField(
            model_name='publicidad',
            name='fecha_inicio',
            field=models.DateField(verbose_name='Fecha de Inicio'),
        ),
        migrations.AlterField(
            model_name='publicidad',
            name='nombre_cliente',
            field=models.CharField(max_length=150, verbose_name='Nombre del Cliente'),
        ),
        migrations.AlterField(
            model_name='publicidad',
            name='tipo',
            field=models.CharField(choices=[('WEB', 'Web'), ('RADIAL', 'Radial')], max_length=10, verbose_name='Tipo de Publicidad'),
        ),
        migrations.AddField(
            model_name='archivopublicidadradial',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos', to='publicidad.itemsolicitudradial', verbose_name='Item de Solicitud'),
        ),
        migrations.AddField(
            model_name='imagenpublicidadweb',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes_web', to='publicidad.itemsolicitudweb', verbose_name='Item de Solicitud'),
        ),
        migrations.AddField(
            model_name='publicidadweb',
            name='publicidad',
            field=models.OneToOneField(limit_choices_to={'tipo': 'WEB'}, on_delete=django.db.models.deletion.CASCADE, related_name='web_config', to='publicidad.publicidad'),
        ),
        migrations.AddField(
            model_name='solicitudpublicidadradial',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_publicidad_radial', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='itemsolicitudradial',
            name='solicitud',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_radial', to='publicidad.solicitudpublicidadradial', verbose_name='Solicitud'),
        ),
        migrations.AddField(
            model_name='solicitudpublicidadweb',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_publicidad_web', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='itemsolicitudweb',
            name='solicitud',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_web', to='publicidad.solicitudpublicidadweb', verbose_name='Solicitud'),
        ),
        migrations.AddField(
            model_name='itemsolicitudradial',
            name='ubicacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items_solicitud_radial', to='publicidad.ubicacionpublicidadradial', verbose_name='Ubicación'),
        ),
        migrations.AddField(
            model_name='itemsolicitudweb',
            name='ubicacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items_solicitud_web', to='publicidad.ubicacionpublicidadweb', verbose_name='Ubicación'),
        ),
        migrations.DeleteModel(
            name='ImagenPublicidad',
        ),
        migrations.DeleteModel(
            name='UbicacionPublicidad',
        ),
        migrations.DeleteModel(
            name='ItemSolicitud',
        ),
        migrations.DeleteModel(
            name='PublicidadRadial',
        ),
        migrations.DeleteModel(
            name='SolicitudPublicidad',
        ),
        migrations.AddIndex(
            model_name='solicitudpublicidadradial',
            index=models.Index(fields=['usuario'], name='solicitud_p_usuario_a11f17_idx'),
        ),
        migrations.AddIndex(
            model_name='solicitudpublicidadradial',
            index=models.Index(fields=['estado'], name='solicitud_p_estado_5b32ef_idx'),
        ),
        migrations.AddIndex(
            model_name='solicitudpublicidadradial',
            index=models.Index(fields=['fecha_solicitud'], name='solicitud_p_fecha_s_7050ea_idx'),
        ),
        migrations.AddConstraint(
            model_name='solicitudpublicidadradial',
            constraint=models.CheckConstraint(condition=models.Q(('fecha_fin_solicitada__gte', models.F('fecha_inicio_solicitada'))), name='solicitud_radial_fechas_validas'),
        ),
        migrations.AddIndex(
            model_name='solicitudpublicidadweb',
            index=models.Index(fields=['usuario'], name='solicitud_p_usuario_15b0b9_idx'),
        ),
        migrations.AddIndex(
            model_name='solicitudpublicidadweb',
            index=models.Index(fields=['estado'], name='solicitud_p_estado_93c699_idx'),
        ),
        migrations.AddIndex(
            model_name='solicitudpublicidadweb',
            index=models.Index(fields=['fecha_solicitud'], name='solicitud_p_fecha_s_3ba559_idx'),
        ),
        migrations.AddConstraint(
            model_name='solicitudpublicidadweb',
            constraint=models.CheckConstraint(condition=models.Q(('fecha_fin_solicitada__gte', models.F('fecha_inicio_solicitada'))), name='solicitud_web_fechas_validas'),
        ),
        migrations.AddIndex(
            model_name='itemsolicitudradial',
            index=models.Index(fields=['solicitud'], name='item_solici_solicit_b9be7c_idx'),
        ),
        migrations.AddIndex(
            model_name='itemsolicitudradial',
            index=models.Index(fields=['ubicacion'], name='item_solici_ubicaci_13c9c2_idx'),
        ),
        migrations.AddIndex(
            model_name='itemsolicitudweb',
            index=models.Index(fields=['solicitud'], name='item_solici_solicit_d6c289_idx'),
        ),
        migrations.AddIndex(
            model_name='itemsolicitudweb',
            index=models.Index(fields=['ubicacion'], name='item_solici_ubicaci_ea1949_idx'),
        ),
    ]
