#generated by django 5.2.7 on 2025-11-08 18:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicidad', '0008_publicidadradial_remove_archivopublicidadradial_item_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudpublicidadweb',
            name='aprobado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_publicidad_web_aprobadas', to=settings.AUTH_USER_MODEL, verbose_name='Aprobado por'),
        ),
        migrations.AddField(
            model_name='solicitudpublicidadweb',
            name='fecha_aprobacion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Aprobación'),
        ),
        migrations.AddField(
            model_name='solicitudpublicidadweb',
            name='publicacion',
            field=models.OneToOneField(blank=True, limit_choices_to={'tipo': 'WEB'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitud_web', to='publicidad.publicidad', verbose_name='Campaña Publicada'),
        ),
    ]
