# Generated by Django 5.2.7 on 2025-11-11 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicidad', '0010_tipoubicacion_alter_ubicacionpublicidadweb_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicidadweb',
            name='formato',
            field=models.CharField(max_length=200, verbose_name='Formato (ej: 728x90)'),
        ),
    ]
