# Generated by Django 5.2.7 on 2025-11-29 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publicidad', '0010_link_publicidad_to_solicitud'),
        ('publicidad', '0011_alter_publicidadweb_formato'),
    ]

    operations = [
    ]
