# Generated by Django 5.2.7 on 2025-12-01 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publicidad', '0012_merge_20251129_1821'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PublicidadRadial',
        ),
    ]
