# Generated by Django 5.2.6 on 2025-11-04 18:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('contacto', 'Mensaje de Contacto'), ('banda', 'Banda Emergente'), ('articulo', 'Articulo Nuevo'), ('programa', 'Cambio en Programacion'), ('suscripcion', 'Nueva Suscripcion')], max_length=20)),
                ('titulo', models.CharField(max_length=255)),
                ('mensaje', models.TextField()),
                ('leido', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('enlace', models.CharField(blank=True, max_length=255, null=True)),
                ('content_type', models.CharField(blank=True, max_length=50, null=True)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notificacion',
                'verbose_name_plural': 'Notificaciones',
                'ordering': ['-fecha_creacion'],
                'indexes': [models.Index(fields=['usuario', 'leido'], name='notificatio_usuario_99feb0_idx'), models.Index(fields=['fecha_creacion'], name='notificatio_fecha_c_929fc4_idx')],
            },
        ),
    ]
