#generated by django 5.2.7 on 2025-11-08 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentFilterConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True, help_text='Activar/desactivar filtro automático')),
                ('umbral_toxicidad', models.FloatField(default=0.7, help_text='Umbral de toxicidad (0.0 - 1.0). Mayor = más estricto')),
                ('bloquear_enlaces', models.BooleanField(default=False, help_text='Bloquear mensajes con enlaces')),
                ('modo_accion', models.CharField(choices=[('bloquear', 'Bloquear mensaje'), ('advertir', 'Advertir usuario'), ('revisar', 'Marcar para revisión')], default='bloquear', help_text='Acción a tomar cuando se detecta contenido ofensivo', max_length=20)),
                ('strikes_para_bloqueo', models.IntegerField(default=3, help_text='Número de infracciones antes de bloquear usuario')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración de Filtro',
                'verbose_name_plural': 'Configuraciones de Filtro',
                'db_table': 'filtro_contenido_config',
            },
        ),
        migrations.CreateModel(
            name='InfraccionUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_usuario', models.IntegerField()),
                ('usuario_nombre', models.CharField(max_length=100)),
                ('mensaje_original', models.TextField()),
                ('tipo_infraccion', models.CharField(choices=[('toxicidad_ml', 'Toxicidad detectada por ML'), ('palabra_prohibida', 'Palabra prohibida'), ('enlace_prohibido', 'Enlace prohibido'), ('spam', 'Spam')], max_length=50)),
                ('score_toxicidad', models.FloatField(blank=True, help_text='Score del modelo ML (0.0 - 1.0)', null=True)),
                ('fecha_infraccion', models.DateTimeField(auto_now_add=True)),
                ('accion_tomada', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Infracción de Usuario',
                'verbose_name_plural': 'Infracciones de Usuarios',
                'db_table': 'infracciones_usuario',
                'ordering': ['-fecha_infraccion'],
            },
        ),
        migrations.CreateModel(
            name='PalabraProhibida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('palabra', models.CharField(max_length=100, unique=True)),
                ('severidad', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta')], default='media', max_length=10)),
                ('activa', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Palabra Prohibida',
                'verbose_name_plural': 'Palabras Prohibidas',
                'db_table': 'palabras_prohibidas',
                'ordering': ['palabra'],
            },
        ),
    ]
