# Generated by Django 5.2.6 on 2025-09-04 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('articulo_id', models.IntegerField()),
                ('autor_nombre', models.CharField(max_length=100)),
                ('autor_correo', models.CharField(blank=True, max_length=150, null=True)),
                ('contenido', models.TextField()),
                ('aprobado', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'blog_comentarios',
                'ordering': ['fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('contenido', models.TextField()),
                ('resumen', models.TextField(blank=True, null=True)),
                ('imagen_url', models.CharField(blank=True, max_length=500, null=True)),
                ('autor_id', models.IntegerField(blank=True, null=True)),
                ('autor_nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('categoria', models.CharField(blank=True, max_length=50, null=True)),
                ('tags', models.CharField(blank=True, help_text='Tags separados por comas', max_length=500, null=True)),
                ('publicado', models.BooleanField(default=True)),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'blog_articulos',
                'ordering': ['-fecha_publicacion'],
            },
        ),
    ]
