#generated by django 5.2.7 on 2025-11-10 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0002_reproduccionradio'),
    ]

    operations = [
        migrations.AddField(
            model_name='conductor',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='locutores/', verbose_name='Foto'),
        ),
    ]
