#generated by django 5.2.7 on 2025-11-11 01:25

from django.db import migrations, models


def remove_foto_url_if_exists(apps, schema_editor):
    """elimina el campo foto_url solo si existe"""
    Conductor = apps.get_model('radio', 'Conductor')
    #verificar si el campo existe en la base de datos
    if hasattr(Conductor, 'foto_url'):
        field = Conductor._meta.get_field('foto_url')
        with schema_editor.connection.cursor() as cursor:
            table_name = Conductor._meta.db_table
            column_name = field.column
            cursor.execute(
                "SELECT column_name FROM information_schema.columns WHERE table_name=%s AND column_name=%s",
                [table_name, column_name]
            )
            if cursor.fetchone():
                #si la columna existe, la eliminamos
                schema_editor.remove_field(Conductor, field)


class Migration(migrations.Migration):
    """elimina el campo foto_url de la tabla conductor de manera segura"""
    atomic = False  # Desactiva las transacciones atómicas para esta migración

    dependencies = [
        ('radio', '0003_remove_conductor_foto_url_conductor_foto'),
    ]

    operations = [
        migrations.RunPython(
            remove_foto_url_if_exists,
            #no hacemos nada en la operacion inversa
            migrations.RunPython.noop,
        ),
    ]
