# Generated by Django 5.2.7 on 2025-11-11 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0004_remove_conductor_foto_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conductor',
            name='foto_url',
        ),
    ]
