#generated by django 5.2.7 on 2025-11-13 22:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0005_remove_conductor_foto_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='conductor',
            name='estacion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='conductores', to='radio.estacionradio'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='generomusical',
            name='estacion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='generos_musicales', to='radio.estacionradio'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='programa',
            name='estacion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='programas', to='radio.estacionradio'),
            preserve_default=False,
        ),
    ]
