# Generated by Django 5.2.7 on 2025-11-13 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0006_conductor_estacion_generomusical_estacion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conductor',
            name='estacion',
        ),
        migrations.RemoveField(
            model_name='generomusical',
            name='estacion',
        ),
    ]
