#generated by django 5.2.7 on 2025-11-14 02:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0007_remove_conductor_estacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programa',
            name='estacion',
            field=models.ForeignKey(blank=True, help_text='Este campo se completará automáticamente con la estación de radio existente.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='programas', to='radio.estacionradio'),
        ),
    ]
