# Generated by Django 5.2.7 on 2025-11-11 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='tipo',
            field=models.CharField(choices=[('contacto', 'Mensaje de Contacto'), ('banda', 'Banda Emergente'), ('articulo', 'Articulo Nuevo'), ('programa', 'Cambio en Programacion'), ('suscripcion', 'Nueva Suscripcion'), ('publicidad', 'Solicitud de Publicidad')], max_length=20),
        ),
    ]
