# Generated by Django 5.2.6 on 2025-11-04 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_usuario', models.IntegerField()),
                ('contenido', models.TextField()),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('usuario_nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo', models.CharField(default='user', max_length=20)),
                ('sala', models.CharField(default='general', max_length=50)),
            ],
            options={
                'db_table': 'mensajes',
                'ordering': ['-fecha_envio'],
            },
        ),
    ]
