# Generated by Django 5.2.7 on 2025-11-09 02:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_add_foreign_keys'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='chatmessage',
            new_name='mensajes_id_usua_9a8011_idx',
            old_name='mensajes_usuario_idx',
        ),
        migrations.RenameIndex(
            model_name='chatmessage',
            new_name='mensajes_fecha_e_9e6258_idx',
            old_name='mensajes_fecha_idx',
        ),
        migrations.RenameIndex(
            model_name='chatmessage',
            new_name='mensajes_sala_a877de_idx',
            old_name='mensajes_sala_idx',
        ),
        migrations.RenameIndex(
            model_name='infraccionusuario',
            new_name='infraccione_id_usua_d50600_idx',
            old_name='infracciones_usuario_idx',
        ),
        migrations.RenameIndex(
            model_name='infraccionusuario',
            new_name='infraccione_fecha_i_34195d_idx',
            old_name='infracciones_fecha_idx',
        ),
        migrations.RenameIndex(
            model_name='infraccionusuario',
            new_name='infraccione_tipo_in_364582_idx',
            old_name='infracciones_tipo_idx',
        ),
        migrations.AddField(
            model_name='infraccionusuario',
            name='palabra_prohibida',
            field=models.ForeignKey(blank=True, help_text='Palabra prohibida detectada (si aplica)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='infracciones', to='chat.palabraprohibida'),
        ),
        migrations.AlterField(
            model_name='infraccionusuario',
            name='mensaje',
            field=models.ForeignKey(blank=True, help_text='Mensaje que causó la infracción (null si fue bloqueado)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='infracciones', to='chat.chatmessage'),
        ),
        migrations.AddIndex(
            model_name='infraccionusuario',
            index=models.Index(fields=['palabra_prohibida'], name='infraccione_palabra_281533_idx'),
        ),
    ]
