# Generated by Django 5.2.6 on 2025-09-04 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('correo', models.CharField(max_length=150)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('asunto', models.CharField(max_length=150)),
                ('mensaje', models.TextField()),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(default='nuevo', max_length=20)),
            ],
            options={
                'db_table': 'formulario_contacto',
                'ordering': ['-fecha_envio'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correo', models.CharField(max_length=150, unique=True)),
                ('nombre', models.CharField(blank=True, max_length=100)),
                ('activa', models.BooleanField(default=True)),
                ('fecha_suscripcion', models.DateTimeField(auto_now_add=True)),
                ('token_unsuscribe', models.CharField(blank=True, max_length=100, null=True, unique=True)),
            ],
            options={
                'db_table': 'suscripciones',
                'ordering': ['-fecha_suscripcion'],
            },
        ),
    ]
