# Generated by Django 5.2.7 on 2025-11-07 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ComentarioArticulo',
        ),
    ]
