#generated by django 5.2.6 on 2025-11-04 18:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contact', '0001_initial'),
        ('radio', '0001_initial'),
        ('ubicacion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Integrante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'Integrante',
                'verbose_name_plural': 'Integrantes',
                'db_table': 'integrante',
            },
        ),
        migrations.CreateModel(
            name='BandaEmergente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_banda', models.CharField(max_length=150)),
                ('email_contacto', models.EmailField(max_length=254)),
                ('telefono_contacto', models.CharField(blank=True, max_length=20, null=True)),
                ('mensaje', models.TextField()),
                ('documento_presentacion', models.URLField(blank=True, max_length=500, null=True)),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('fecha_revision', models.DateTimeField(blank=True, null=True)),
                ('comuna', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bandas_emergentes', to='ubicacion.comuna')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bandas_emergentes', to='contact.estado')),
                ('genero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bandas_emergentes', to='radio.generomusical')),
                ('revisado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bandas_revisadas', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bandas_emergentes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Banda Emergente',
                'verbose_name_plural': 'Bandas Emergentes',
                'db_table': 'banda_emergente',
            },
        ),
        migrations.CreateModel(
            name='BandaLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
                ('url', models.URLField(max_length=500)),
                ('banda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='emergente.bandaemergente')),
            ],
            options={
                'verbose_name': 'Link de Banda',
                'verbose_name_plural': 'Links de Bandas',
                'db_table': 'banda_link',
            },
        ),
        migrations.CreateModel(
            name='BandaIntegrante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integrantes', to='emergente.bandaemergente')),
                ('integrante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bandas', to='emergente.integrante')),
            ],
            options={
                'verbose_name': 'Banda-Integrante',
                'verbose_name_plural': 'Bandas-Integrantes',
                'db_table': 'banda_integrante',
            },
        ),
        migrations.AddIndex(
            model_name='bandaemergente',
            index=models.Index(fields=['estado'], name='banda_emerg_estado__abbc8b_idx'),
        ),
        migrations.AddIndex(
            model_name='bandaemergente',
            index=models.Index(fields=['genero'], name='banda_emerg_genero__7e40b0_idx'),
        ),
        migrations.AddIndex(
            model_name='bandaemergente',
            index=models.Index(fields=['usuario'], name='banda_emerg_usuario_9ea2c3_idx'),
        ),
        migrations.AddIndex(
            model_name='bandaemergente',
            index=models.Index(fields=['comuna'], name='banda_emerg_comuna__d287e0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='bandaintegrante',
            unique_together={('banda', 'integrante')},
        ),
    ]
