# Generated by Django 5.2.7 on 2025-11-09 23:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0002_delete_comentarioarticulo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='usuarios_que_vieron',
            field=models.ManyToManyField(blank=True, related_name='articulos_vistos', to=settings.AUTH_USER_MODEL, verbose_name='Usuarios que vieron este artículo'),
        ),
    ]
