# Generated by Django 5.2.7 on 2025-11-09 23:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReproduccionRadio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_reproduccion', models.DateTimeField(auto_now_add=True)),
                ('estacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reproducciones', to='radio.estacionradio')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reproducciones_radio', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reproducción de Radio',
                'verbose_name_plural': 'Reproducciones de Radio',
                'db_table': 'reproduccion_radio',
                'indexes': [models.Index(fields=['estacion'], name='reproduccio_estacio_8b882c_idx'), models.Index(fields=['usuario'], name='reproduccio_usuario_4e8e63_idx'), models.Index(fields=['fecha_reproduccion'], name='reproduccio_fecha_r_987087_idx')],
                'unique_together': {('estacion', 'usuario')},
            },
        ),
    ]
