# Generated by Django 5.0.4 on 2025-09-19 20:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BandaEmergente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_banda', models.CharField(max_length=150)),
                ('integrantes', models.TextField(blank=True, null=True)),
                ('genero', models.CharField(max_length=50)),
                ('ciudad', models.CharField(blank=True, max_length=100, null=True)),
                ('correo_contacto', models.EmailField(max_length=254)),
                ('telefono_contacto', models.CharField(blank=True, max_length=20, null=True)),
                ('mensaje', models.TextField()),
                ('links', models.TextField(blank=True, null=True)),
                ('press_kit', models.FileField(blank=True, null=True, upload_to='presskits/')),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de revisión'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=10)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bandas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Banda Emergente',
                'verbose_name_plural': 'Bandas Emergentes',
                'db_table': 'bandas_emergentes',
            },
        ),
    ]
