# Generated by Django 5.2.6 on 2025-11-04 19:43

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('radio', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EspacioPublicitario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre del Espacio')),
                ('codigo', models.SlugField(max_length=80, unique=True, verbose_name='Código')),
                ('ubicacion', models.CharField(choices=[('header', 'Encabezado'), ('top_page', 'Parte Superior'), ('sidebar_left', 'Barra Lateral Izquierda'), ('sidebar_right', 'Barra Lateral Derecha'), ('content', 'Contenido'), ('footer', 'Pie de Página')], max_length=30, verbose_name='Ubicación')),
                ('ancho_px', models.PositiveIntegerField(verbose_name='Ancho (px)')),
                ('alto_px', models.PositiveIntegerField(verbose_name='Alto (px)')),
                ('formatos_permitidos', models.JSONField(default=list, help_text='Ej: ["jpg","png","webp","gif"]', verbose_name='Formatos Permitidos')),
                ('peso_max_mb', models.DecimalField(decimal_places=2, default=Decimal('2.00'), max_digits=5, verbose_name='Peso Máximo (MB)')),
                ('precio_por_dia', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Precio por Día')),
                ('activo', models.BooleanField(default=True, verbose_name='¿Activo?')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Espacio Publicitario',
                'verbose_name_plural': 'Espacios Publicitarios',
                'db_table': 'espacio_publicitario',
                'indexes': [models.Index(fields=['codigo'], name='espacio_pub_codigo_e41cf0_idx'), models.Index(fields=['activo'], name='espacio_pub_activo_02cc76_idx'), models.Index(fields=['ubicacion'], name='espacio_pub_ubicaci_c3dcf8_idx')],
            },
        ),
        migrations.CreateModel(
            name='Publicidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cliente', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('tipo', models.CharField(choices=[('WEB', 'Web'), ('RADIAL', 'Radial')], max_length=10)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('activo', models.BooleanField(default=True)),
                ('costo_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('archivo_media', models.URLField(blank=True, max_length=500, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publicidades', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Publicidad',
                'verbose_name_plural': 'Publicidades',
                'db_table': 'publicidad',
            },
        ),
        migrations.CreateModel(
            name='PublicidadRadial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duracion_segundos', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('valor_por_segundo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('costo_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('horario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publicidades', to='radio.horarioprograma')),
                ('publicidad', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='radial_config', to='publicidad.publicidad')),
            ],
            options={
                'verbose_name': 'Publicidad Radial',
                'verbose_name_plural': 'Publicidades Radiales',
                'db_table': 'publicidad_radial',
            },
        ),
        migrations.CreateModel(
            name='PublicidadWeb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ubicacion', models.CharField(choices=[('banner_superior', 'Banner Superior'), ('lateral', 'Lateral'), ('footer', 'Footer')], max_length=50)),
                ('formato', models.CharField(blank=True, max_length=50, null=True)),
                ('url_destino', models.URLField(blank=True, max_length=500, null=True)),
                ('impresiones', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('clics', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('costo_por_dia', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('publicidad', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='web_config', to='publicidad.publicidad')),
            ],
            options={
                'verbose_name': 'Publicidad Web',
                'verbose_name_plural': 'Publicidades Web',
                'db_table': 'publicidad_web',
            },
        ),
        migrations.CreateModel(
            name='SolicitudPublicidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cliente', models.CharField(max_length=150, verbose_name='Nombre del Cliente')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo Electrónico')),
                ('telefono', models.CharField(blank=True, max_length=50, null=True, verbose_name='Teléfono')),
                ('whatsapp', models.CharField(blank=True, max_length=50, null=True, verbose_name='WhatsApp')),
                ('mensaje_cliente', models.TextField(blank=True, null=True, verbose_name='Mensaje Adicional')),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('enviada', 'Enviada'), ('en_revision', 'En Revisión'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada'), ('cancelada', 'Cancelada')], default='borrador', max_length=15, verbose_name='Estado')),
                ('canal', models.CharField(choices=[('formulario_web', 'Formulario Web'), ('administrador', 'Creado por Administrador')], default='formulario_web', max_length=20, verbose_name='Canal de Creación')),
                ('monto_estimado', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Monto Estimado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Solicitud de Publicidad',
                'verbose_name_plural': 'Solicitudes de Publicidad',
                'db_table': 'solicitud_publicidad',
            },
        ),
        migrations.CreateModel(
            name='ItemSolicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de Inicio')),
                ('fecha_fin', models.DateField(verbose_name='Fecha de Finalización')),
                ('precio_dia', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio por Día')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Subtotal')),
                ('url_destino', models.URLField(blank=True, max_length=500, null=True, verbose_name='URL de Destino')),
                ('notas', models.TextField(blank=True, null=True, verbose_name='Notas Adicionales')),
                ('espacio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items_solicitud', to='publicidad.espaciopublicitario', verbose_name='Espacio Publicitario')),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='publicidad.solicitudpublicidad', verbose_name='Solicitud')),
            ],
            options={
                'verbose_name': 'Ítem de Solicitud',
                'verbose_name_plural': 'Ítems de Solicitud',
                'db_table': 'item_solicitud',
            },
        ),
        migrations.CreateModel(
            name='CreatividadPublicitaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.ImageField(upload_to='publicidad/creatividades/', verbose_name='Archivo')),
                ('ancho_px_detectado', models.PositiveIntegerField(blank=True, null=True, verbose_name='Ancho Detectado (px)')),
                ('alto_px_detectado', models.PositiveIntegerField(blank=True, null=True, verbose_name='Alto Detectado (px)')),
                ('formato_detectado', models.CharField(blank=True, max_length=20, null=True, verbose_name='Formato Detectado')),
                ('valido', models.BooleanField(default=True, verbose_name='¿Válido?')),
                ('razon_invalidez', models.TextField(blank=True, null=True, verbose_name='Razón de Invalidez')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Subida')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creatividades', to='publicidad.itemsolicitud', verbose_name='Ítem de Solicitud')),
            ],
            options={
                'verbose_name': 'Creatividad Publicitaria',
                'verbose_name_plural': 'Creatividades Publicitarias',
                'db_table': 'creatividad_publicitaria',
                'indexes': [models.Index(fields=['item'], name='creatividad_item_id_9df390_idx'), models.Index(fields=['fecha_subida'], name='creatividad_fecha_s_20535a_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='publicidad',
            index=models.Index(fields=['usuario'], name='publicidad_usuario_0bcea4_idx'),
        ),
        migrations.AddIndex(
            model_name='publicidad',
            index=models.Index(fields=['tipo'], name='publicidad_tipo_d3c5ee_idx'),
        ),
        migrations.AddIndex(
            model_name='publicidad',
            index=models.Index(fields=['activo'], name='publicidad_activo_8d42af_idx'),
        ),
        migrations.AddIndex(
            model_name='publicidad',
            index=models.Index(fields=['fecha_inicio', 'fecha_fin'], name='publicidad_fecha_i_2360ac_idx'),
        ),
        migrations.AddConstraint(
            model_name='publicidad',
            constraint=models.CheckConstraint(condition=models.Q(('fecha_fin__gte', models.F('fecha_inicio'))), name='publicidad_fechas_validas'),
        ),
        migrations.AddIndex(
            model_name='publicidadradial',
            index=models.Index(fields=['horario'], name='publicidad__horario_0c7320_idx'),
        ),
        migrations.AddIndex(
            model_name='solicitudpublicidad',
            index=models.Index(fields=['estado'], name='solicitud_p_estado_d612f3_idx'),
        ),
        migrations.AddIndex(
            model_name='solicitudpublicidad',
            index=models.Index(fields=['fecha_creacion'], name='solicitud_p_fecha_c_e29db5_idx'),
        ),
        migrations.AddIndex(
            model_name='itemsolicitud',
            index=models.Index(fields=['solicitud'], name='item_solici_solicit_f6ca04_idx'),
        ),
        migrations.AddIndex(
            model_name='itemsolicitud',
            index=models.Index(fields=['espacio'], name='item_solici_espacio_80b5f7_idx'),
        ),
        migrations.AddConstraint(
            model_name='itemsolicitud',
            constraint=models.CheckConstraint(condition=models.Q(('fecha_fin__gte', models.F('fecha_inicio'))), name='fechas_validas_item_solicitud'),
        ),
    ]
