# Generated by Django 5.2.7 on 2025-11-07 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publicidad', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemsolicitud',
            name='espacio',
        ),
        migrations.RemoveField(
            model_name='itemsolicitud',
            name='solicitud',
        ),
        migrations.RemoveField(
            model_name='solicitudpublicidad',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='CreatividadPublicitaria',
        ),
        migrations.DeleteModel(
            name='EspacioPublicitario',
        ),
        migrations.DeleteModel(
            name='ItemSolicitud',
        ),
        migrations.DeleteModel(
            name='SolicitudPublicidad',
        ),
    ]
