# Generated by Django 5.2.7 on 2025-11-08 16:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicidad', '0004_remove_publicidad_publicidad_usuario_0bcea4_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicidad',
            name='clics',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='publicidad',
            name='formato',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='publicidad',
            name='impresiones',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='publicidad',
            name='url_destino',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.DeleteModel(
            name='PublicidadWeb',
        ),
    ]
