# Generated by Django 5.2.7 on 2025-11-08 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicidad', '0005_publicidad_clics_publicidad_formato_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemsolicitud',
            name='formato',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
