# Generated by Django 5.2.7 on 2025-11-08 17:58

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicidad', '0007_archivopublicidadradial_imagenpublicidadweb_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicidadRadial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duracion', models.IntegerField(help_text='Duración del spot en segundos', verbose_name='Duración en segundos')),
                ('repeticiones_diarias', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Repeticiones diarias')),
                ('archivo_audio', models.FileField(help_text='Archivo de audio para la publicidad radial', upload_to='publicidad/radial/audios/%Y/%m/', verbose_name='Archivo de Audio')),
                ('reproducciones', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Número de Reproducciones')),
            ],
            options={
                'verbose_name': 'Configuración Radial',
                'verbose_name_plural': 'Configuraciones Radiales',
                'db_table': 'publicidad_radial',
            },
        ),
        migrations.RemoveField(
            model_name='archivopublicidadradial',
            name='item',
        ),
        migrations.RemoveField(
            model_name='itemsolicitudradial',
            name='solicitud',
        ),
        migrations.RemoveField(
            model_name='itemsolicitudradial',
            name='ubicacion',
        ),
        migrations.RemoveField(
            model_name='solicitudpublicidadradial',
            name='usuario',
        ),
        migrations.AlterModelOptions(
            name='itemsolicitudweb',
            options={'ordering': ['id'], 'verbose_name': 'Item de Solicitud Web', 'verbose_name_plural': 'Items de Solicitud Web'},
        ),
        migrations.RemoveIndex(
            model_name='itemsolicitudweb',
            name='item_solici_solicit_d6c289_idx',
        ),
        migrations.RemoveIndex(
            model_name='itemsolicitudweb',
            name='item_solici_ubicaci_ea1949_idx',
        ),
        migrations.RemoveIndex(
            model_name='solicitudpublicidadweb',
            name='solicitud_p_usuario_15b0b9_idx',
        ),
        migrations.AddField(
            model_name='publicidadradial',
            name='publicidad',
            field=models.OneToOneField(limit_choices_to={'tipo': 'RADIAL'}, on_delete=django.db.models.deletion.CASCADE, related_name='radial_config', to='publicidad.publicidad'),
        ),
        migrations.DeleteModel(
            name='ArchivoPublicidadRadial',
        ),
        migrations.DeleteModel(
            name='ItemSolicitudRadial',
        ),
        migrations.DeleteModel(
            name='UbicacionPublicidadRadial',
        ),
        migrations.DeleteModel(
            name='SolicitudPublicidadRadial',
        ),
    ]
